export const Employees = [
  {
    employeeId: 'NIX001', 
    name: "Shubham Shukla",
    designation: "CEO & Co-founder",
    img: "assets/img/team/Shubham.jpg",
    socials: [],
  },
  {
    employeeId: 'NIX001.1', 
    name: "Rajat Shukla",
    designation: "Co-founder",
    img: "assets/img/team/Rajat.jpg",
    socials: [],
  },
  {
    employeeId: 'NIX001.2', 
    name: "Arpit Tyagi",
    designation: "Technical Lead (Frontend)",
    img: "assets/img/team/Arpit.jpg",
    socials: [],
  },
  {
    employeeId: 'NIX001.3', 
    name: "Abhishek Mahra",
    designation: "Technical Lead (Backend)",
    img: "assets/img/team/Abhishek.jpg",
    socials: [],
  },
  {
    employeeId: 'NIX0011', 
    name: "Saloni Srivastava",
    designation: "Head of Operations",
    img: "assets/img/team/Saloni.jpg",
    socials: [],
  },
  {
    employeeId: 'NIX002', 
    name: "Awadhesh Chaurasia",
    designation: "Senior Software Engineer",
    img: "assets/img/team/Awadhesh.jpg",
    socials: [],
  },
  {
    employeeId: 'NIX005', 
    name: "Rahul Srivastava",
    designation: "Senior Software Engineer",
    img: "assets/img/team/Rahul.jpg",
    socials: [],
  },
  {
    employeeId: 'NIX007', 
    name: "Prateek Singh",
    designation: "Product Designer",
    img: "assets/img/team/Prateek.jpg",
    socials: [],
  },
  {
    employeeId: 'NIX003', 
    name: "Manish Chaurasiya",
    designation: "Software Engineer",
    img: "assets/img/team/Manish.jpg",
    socials: [],
  },
  {
    employeeId: 'NIX008', 
    name: "Arun Kumar Gautam",
    designation: "Software Engineer",
    img: "assets/img/team/Arun.jpg",
    socials: [],
  },
  {
    employeeId: 'NIX004', 
    name: "Luv Kumar Gupta",
    designation: "Software Engineer",
    img: "assets/img/team/Luv.jpg",
    socials: [],
  },
  {
    employeeId: 'NIX006', 
    name: "Nadeem Alam",
    designation: "Software Engineer",
    img: "assets/img/team/Nadeem.jpg",
    socials: [],
  },
  {
    employeeId: 'NIX0010', 
    name: "Monika Negi",
    designation: "Digital Marketer",
    img: "assets/img/team/Monika.jpg",
    socials: [],
  },
  {
    employeeId: 'NIX009', 
    name: "Rohit Yadav",
    designation: "Software Engineer",
    img: "assets/img/team/Rohit.jpg",
    socials: [],
  },
  {
    employeeId: 'NIX001.4', 
    name: "Sangeeta Gehlot",
    designation: "Software Engineer",
    img: "assets/img/team/Sangeeta.jpg",
    socials: [],
  },
  {
    employeeId: 'NIX001.5', 
    name: "Manmohan Ujala",
    designation: "QA Engineer",
    img: "assets/img/team/Manmohan.jpg",
    socials: [],
  },
  {
    employeeId: 'NIX001.5', 
    name: "Jack",
    designation: "Therapist",
    img: "assets/img/team/Jack.jpg",
    socials: [],
  },
];
